### ISSUE TITLE
@hyperdx/node-opentelemetry has an absolutely gigantic install size

### ISSUE THREAD

**Issue by mprast** [hyperdxio/hyperdx-js#84]
It's so big it times out on [packagephobia](https://packagephobia.com/). Based on the size of my container before and after it looks like it's > 300MB, which is 6x the size of the entire rest of my app. HyperDX looks cool but I can't justify exploding the size of my backend for it; I figure I'll just try to make do with the standard otel packages, and failing that probably just use Sentry.

Are there any plans to try and bring the install size down?

**Comment by wrn14897** [comment]
Hi @mprast , the bundle size should be 3x smaller in the latest release `v0.7.0` (~50M). Thanks for bringing the issue up.
